import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import 'antd/dist/reset.css';
import { ToastContainer } from 'react-toastify';
import { AntdProvider } from './providers/AntdProvider';
import '@ant-design/v5-patch-for-react-19';
import './styles/notifications.css';
import { QueryProvider } from './providers/QueryProvider';
import { NotificationProvider } from './providers/NotificationProvider';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "listok",
    description: "Generated by create next app",
    icons: {
        icon: '/favicon.ico',
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <QueryProvider>
                    <AntdProvider>
                        <NotificationProvider>
                            {children}
                            <ToastContainer
                                position="top-right"
                                autoClose={4000}
                                newestOnTop={false}
                                closeOnClick
                                rtl={false}
                                pauseOnFocusLoss
                                draggable
                                pauseOnHover
                                hideProgressBar
                                theme="dark"
                            />
                        </NotificationProvider>
                    </AntdProvider>
                </QueryProvider>
            </body>
        </html>
    );
}
